windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = make-waypaper-float
	match:class = waypaper
	float = yes
}

windowrule = match:class = kitty, border_size = 20
windowrule {
    name = kitty-no-border
	match:class = kitty
	border_size = 0
}

windowrule {
    name = slack-opaque
	match:class = Slack
	opacity = 0.95
}

windowrule {
    name = spotify-opaque
	match:class = spotify
	opacity = 0.95
}

windowrule {
    name = vesktop-opaque
	match:class = vesktop
	opacity = 0.9
}

windowrule {
    name = mission-float
	match:class = io.missioncenter.MissionCenter
	float = yes
	border_size = 0
}

windowrule {
    name = stellarium
	match:class = org.stellarium.stellarium
	float = yes
	border_size = 0
}

windowrule {
    name = floating-windows-no-border
	match:float = true
	border_size = 0
}
