color0 #40484c
color1 #ffb4ab
color2 #89d0ed
color3 #b3cad5
color4 #c4c3eb
color5 #89d0ed
color6 #b3cad5
color7 #dee3e6
color8 #8a9296
color9 #ffb4ab
color10 #89d0ed
color11 #b3cad5
color12 #c4c3eb
color13 #89d0ed
color14 #b3cad5
color15 #dee3e6

cursor                #dee3e6
cursor_text_color     #0f1416
background            #0f1416
foreground            #dee3e6
selection_foreground  #c0c8cc
selection_background  #40484c
active_border_color   #89d0ed
inactive_border_color #40484c
url_color             #89d0ed

active_tab_foreground   #003544
active_tab_background   #89d0ed
inactive_tab_foreground #c0c8cc
inactive_tab_background #40484c
cursor_trail_color      #c0c8cc
